name: Build
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: go build .